refactor: Improve service connection selection logic in set-gcp-creds script

diff --git a/bin/set-gcp-creds b/bin/set-gcp-creds
--- a/bin/set-gcp-creds
+++ b/bin/set-gcp-creds
@@ -40,50 +40,52 @@ declare -a scnames
 mkdir -p "$credspath"
 
 if [[ -n $1 ]]; then
-  # Use the provided parameter directly
-  scpath="$(get-vault-key get "$1" "creds.json" 2> /dev/null)"
+  scname="$1"
 
-  [[ -n $scpath ]] || die "Could not find credentials for '$1'"
-  credsfile="$credspath/${1//\//-}.json"
+else
+  [[ -f azure-pipelines.yml ]] \
+    || die "No parameter provided and no azure-pipelines.yml found in current directory"
 
-elif [[ -f azure-pipelines.yml ]]; then
   # Extract service connection names from azure-pipelines.yml
   readarray -t scnames < <(grep -i "tfServiceConnectionName:" azure-pipelines.yml |
                           sed -E '
-                            s/#.*$//;                         # Remove comments
                             s/^[^:]*://;                      # Get value after colon
-                            s/^[[:space:]]*|[[:space:]]*$//g; # Trim whitespace
+                            s/#.*$//;                         # Remove comments
                             s/["'\'']//g;                     # Remove quotes
+                            s/^[[:space:]]*|[[:space:]]*$//g; # Trim whitespace
                             s/^(sandbox|zions)-cloud-(dev|test)?-//; # Remove prefix
-                            s/[-_]/[_-]/g;                    # Replace dashes/underscores with character class
+                            s/[-_]/[-_]/g;                    # Replace dashes/underscores with character class
                             /^$/d                             # Remove empty lines
                           ')
 
-  # Handle case with no service connections found
-  [[ ${#scnames[@]} -eq 0 ]] && die "No service connection names found in azure-pipelines.yml"
+  if [[ ${#scnames[@]} -eq 0 ]]; then
+    die "No service connection names found in azure-pipelines.yml"
 
-  # If multiple service connections, let user select one
-  if [[ ${#scnames[@]} -gt 1 ]]; then
+  elif [[ ${#scnames[@]} -eq 1 ]]; then
+    scname="${scnames[0]}"
+
+  else
     echo "Multiple service connections found:"
     PS3="Select a service connection (0 to cancel): "
+
     select name in "${scnames[@]}" "Cancel"; do
       if [[ "$REPLY" == "0" || "$name" == "Cancel" ]]; then
         die "Operation cancelled by user"
+
       elif [[ -n "$name" ]]; then
         scname="$name"
         break
       fi
     done
-  else
-    scname="${scnames[0]}"
-    echo "Using service connection: $scname"
   fi
-
-  # Determine path and credentials file name
-  credsfile="$credspath/sandbox-$scname.json"
-else
-  die "No parameter provided and no azure-pipelines.yml found in current directory"
 fi
+
+#-----------------------------------------------------------------------------
+# Use the provided parameter directly
+scpath="$(get-vault-key get "$scname" "creds.json" 2> /dev/null)"
+
+[[ -n $scpath ]] || die "Could not find credentials for '$1'"
+credsfile="$credspath/${1//\//-}.json"
 
 #-----------------------------------------------------------------------------
 # Get credentials and save to file
