various improvements and fixes, and a couple of references added

diff --git a/.bash_sources.d/git b/.bash_sources.d/git
--- a/.bash_sources.d/git
+++ b/.bash_sources.d/git
@@ -3,31 +3,134 @@
 # Aliases and functions for git
 
 # Check the following for more ideas:
-#
+
 # https://gist.github.com/chrismccoy/8775224
 # https://gitlab.com/mikegerwitz/git-shortmaps
 # https://github.com/scmbreeze/scm_breeze
 
-GIT=$(command -v git 2> /dev/null)
+GIT=$(command -v git 2>/dev/null)
 
-if [ -n $GIT ]; then
+if [[ -n $GIT ]]; then
+
+  # shellcheck disable=SC1090
+  source "$(dirname "$(realpath ~/.bash_profile)")/utility"
 
   function git_remove_missing_files() { git ls-files -d -z | xargs -0 git update-index --remove; }
 
+  function gtoplevel() {
+    git rev-parse --show-toplevel 2> /dev/null || {
+      warn "Not in a git repository."
+      return 1
+    }
+
+    return 0
+  }
+
   # Go to current git repo toplevel directory.
-  function gtl () { cd $(git rev-parse --show-toplevel); }
+  function gtl() {
+    local dir
+    dir="$(gtoplevel)" || return 1
+
+    cd "$dir" || {
+      warn "Unable to change to $dir"
+      return 1
+    }
+  }
 
   # Go to current git toplevel directory, perform the git command and return
   # to the original directory.
-  function git_cmd_return () { gtl ; git "$@" ; cd - > /dev/null ; }
+  # XXX: Do any functions need this?
+  function git_cmd_return() {
+    gtl || return 1
+    debug "changed to $PWD"
+    debug "git $*"
+    git "$@"
+    # shellcheck disable=SC2164
+    cd - >/dev/null
+  }
 
-  function ga  () { git_cmd_return add "$@" ; }
-  function gca () { git_cmd_return commit -a -v -m "$@" ; }
-  function gc  () { git_cmd_return commit -v -m "$@" ; }
-  function gco () { git_cmd_return checkout "$@" ; }
-  function gf  () { git_cmd_return fetch ; }
-  function gmv () { git_cmd_return mv "$@" ; }
-  function grm () { git_cmd_return rm "$@" ; }
+  vim_bundles='.vim/bundle'
+
+  function gsubadd() {
+    gtl || return 1
+
+    if (($# < 2)); then
+      cat <<EOH
+  Usage: gsubadd <repo> <submodule> <branch>
+
+  This function will add the repository in $vim_bundles
+  and set the various settings in .gitmodule for that submodule.
+
+  Currently, those are:
+
+  ignore = dirty
+
+EOH
+    fi
+
+    repo=$1
+    name=$2
+    name_dir="$vim_bundles/$name"
+    branch=$3
+
+    [[ -d $name_dir ]] || mkdir -p "$name"
+
+    debug "git submodule add -b \"$branch\" \"$repo\" \"$name_dir\""
+    git submodule add -b "$branch" "$repo" "$name_dir"
+
+    debug "git config -f .gitmodules submodule.\"$name_dir\".ignore dirty"
+    git config -f .gitmodules submodule."$name_dir".ignore dirty
+
+    debug "git add .gitmodules"
+    git add .gitmodules
+
+    debug "git commit -m \"added $name submodule\""
+    git commit -m "added $name submodule"
+
+    # shellcheck disable=SC2164
+    cd - >/dev/null
+  }
+
+  function gsubrm() {
+    gtl || return 1
+
+    [[ -z $1 ]] && {
+      warn "Must pass a bundle to be removed"
+      return 1
+    }
+
+    name=$1
+    name_dir="$vim_bundles/$name"
+
+    [[ -d $name_dir ]] || {
+      warn "$name_dir does not exist"
+      return 1
+    }
+
+    debug "git rm $name_dir"
+    git rm "$name_dir"
+
+    debug "rm -fr .git/modules/$vim_bundles/$name"
+    rm -fr ".git/modules/$vim_bundles/$name"
+
+    debug "git config -f .git/config --remove-section submodule.\"$name_dir\""
+    git config -f .git/config --remove-section submodule."$name_dir" 2>/dev/null
+
+    debug "git commit -m \"removed $name bundle\""
+    git commit -m "removed $name bundle"
+
+    # shellcheck disable=SC2164
+    cd - >/dev/null
+  }
+
+  # Do any of these need git_cmd_return?
+  function ga() { git add "$@"; }
+  function gca() { git commit -a -v -m "$@"; }
+  function gc() { git commit -v -m "$@"; }
+  function gco() { git checkout "$@"; }
+  function gf() { git fetch --all --tags; }
+  function gmv() { git mv "$@"; }
+  function grm() { git rm "$@"; }
 
   alias gall='git add .'
   alias gba='git branch -ra -v'
diff --git a/bin/update_task b/bin/update_task
--- a/bin/update_task
+++ b/bin/update_task
@@ -1,23 +1,39 @@
 #!/bin/bash
 
-BASE_DIR="$HOME/projects/taskwarrior/task"
+TASKW_DIR="$HOME/projects/taskwarrior/task"
+TIMEW_DIR="$HOME/projects/taskwarrior/timewarrior"
 
-cd "$BASE_DIR" || {
-  echo "Unable to cd to $BASE_DIR, exiting."
+function update() {
+  # start clean
+  git clean -xf
+
+  # update repo
+  git fetch --all --tags
+  git pull --recurse-submodules
+  git submodule update
+
+  # make the project
+  cmake -DCMAKE_BUILD_TYPE=release .
+  make
+  make test && sudo make install
+}
+
+set_title 'update taskwarrior'
+
+cd "$TASKW_DIR" || {
+  echo "Unable to cd to $TASKW_DIR, exiting."
   exit 1
 }
 
-set_title "$(basename "$0")"
+update
 
-# start clean
-git clean -xf
+set_title 'update timewarrior'
 
-# update flexget
-git fetch --all --tags
-git pull
+cd "$TIMEW_DIR" || {
+  echo "Unable to cd to $TIMEW_DIR, exiting."
+  exit 1
+}
 
-cmake -DCMAKE_BUILD_TYPE=release .
-make
-make test && sudo make install
+update
 
 set_title 'done_updating'
