refactor: Modify vault paths structure to support directories and keys with same names

diff --git a/get-vault-key/testit b/get-vault-key/testit
--- a/get-vault-key/testit
+++ b/get-vault-key/testit
@@ -2,15 +2,34 @@
 
 cache_dir="$PWD"
 paths_file='mock-vault-paths.json'
-mode=
 
-case "$1" in
-  debug) mode='pudb' ;;
-  echo) mode='echo' ;;
-esac
+# Default mode is null (just run the script)
+mode=${1:-null}
 
-$mode ./get-vault-key.py \
-  list "production" \
+cmd="./get-vault-key.py \
   --cache-dir \"$cache_dir\" \
-  --paths-file \"$paths_file\"
+  --paths-file \"$paths_file\" \
+  list root1/production"
+
+case "$mode" in
+  debug)
+    # Start with pudb debugger
+    python3 -m pudb ./get-vault-key.py \
+      --cache-dir "$cache_dir" \
+      --paths-file "$paths_file" \
+      list root1/production
+    ;;
+  echo)
+    # Just echo the command
+    echo "$cmd"
+    ;;
+  null|"")
+    # Just run the command
+    eval "$cmd"
+    ;;
+  *)
+    echo "Error: Unknown mode '$mode'. Use one of: debug, echo, null"
+    exit 1
+    ;;
+esac
 
